# Generated by Django 3.2.7 on 2021-10-14 12:42

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to=post.models.post_directory_path)),
                ('external_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
