# Generated by Django 3.2.7 on 2021-10-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
        ('user', '0002_auto_20211011_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='things_user_likes',
            field=models.ManyToManyField(blank=True, related_name='liked_things', to='interest.Interest'),
        ),
    ]
